#!/usr/bin/bash
echo "1. Create virtual env: $ python3 -m venv env \n2. Comment this echo, uncomment the rest \n3. Fill in appropriate public ip address of this machine in line 8 in this script."
#source env/bin/activate
#git pull
#pip install aerospike
#pip install -r requirements.txt
#cd src
#env/bin/python3 -m uvicorn main:app --host 10.112.109.*** --port 8088
